src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table
 */
class Task
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Vous devez saisir un titre.")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez saisir du contenu.")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDone;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     */
    private $User;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): Task
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title): Task
    {
        $this->title = $title;

        return $this;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content): Task
    {
        $this->content = $content;

        return $this;
    }

    public function isDone(): bool
    {
        return $this->isDone;
    }

    public function toggle($flag): Task
    {
        $this->isDone = $flag;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): Task
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content', TextareaType::class)
        ;

        //Avoid code quality error :/ remove if needed
        $options = null;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TaskController extends AbstractController
{
    /**
     * @Route("/tasks", name="task_list")
     *
     * @return Response
     */
    public function listAction(): Response
    {
        return $this->render(
            'task/list.html.twig',
            ['tasks' => $this->getDoctrine()->getRepository(Task::class)->findBy([
                'isDone' => false
            ])]
        );
    }

    /**
     * @Route("/tasks/done", name="task_list_done")
     *
     * @return Response
     */
    public function listDoneAction(): Response
    {
        return $this->render(
            'task/list.html.twig',
            ['tasks' => $this->getDoctrine()->getRepository(Task::class)->findBy([
                'isDone' => true
            ])]
        );
    }

    /**
     * @Route("/tasks/create", name="task_create")
     *
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function createAction(Request $request)
    {
        $form = $this->createForm(TaskType::class, $task = new Task());

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $task->setUser($this->getUser());
            $manager = $this->getDoctrine()->getManager();

            $manager->persist($task);
            $manager->flush();

            $this->addFlash('success', 'La tâche a été bien été ajoutée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/tasks/{id}/edit", name="task_edit")
     *
     * @param Task $task
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function editAction(Task $task, Request $request)
    {
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'La tâche a bien été modifiée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/edit.html.twig', [
            'form' => $form->createView(),
            'task' => $task,
        ]);
    }

    /**
     * @Route("/tasks/{id}/toggle", name="task_toggle")
     *
     * @param Task $task
     * @return RedirectResponse
     */
    public function toggleTaskAction(Task $task): RedirectResponse
    {
        $task->toggle(!$task->isDone());
        $this->getDoctrine()->getManager()->flush();

        $this->addFlash(
            'success', sprintf(
                'La tâche %s a bien été marquée comme %s terminée.',
                $task->getTitle(), $task->isDone() ? '' : 'non'
            )
        );

        return $this->redirectToRoute('task_list');
    }

    /**
     * @Route("/tasks/{id}/delete", name="task_delete")
     *
     * @param Task $task
     * @return RedirectResponse
     */
    public function deleteTaskAction(Task $task): RedirectResponse
    {
        $this->denyAccessUnlessGranted('delete', $task);

        $manager = $this->getDoctrine()->getManager();
        $manager->remove($task);
        $manager->flush();

        $this->addFlash('success', 'La tâche a bien été supprimée.');

        return $this->redirectToRoute('task_list');
    }
}

templates/task/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_create')}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Ajouter</button>
        {{ form_end(form) }}

        <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
    </div>
{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h4>créée par <b>{{ task.user.username|default('anonymous user') }}</b></h4>
    <div class="row col-sm-12">
        {{ form_start(form, {'action' : path('task_edit', { 'id' : task.id })}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Modifier</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}" alt="todo list">{% endblock %}

{% block body %}
    <div class="row mb-2">
        <div class="col-sm-12">
            <a href="{{ path('task_create') }}" class="btn btn-info pull-right">Créer une tâche</a>
        </div>
    </div>
    <div class="row">
        {% for task in tasks %}
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail my-1">
                <div class="caption">
                    <h4 class="pull-right">
                        {% if task.isDone %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span class="glyphicon glyphicon-remove"></span>{% endif %}
                    </h4>
                    <h4><a href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a></h4>
                    <p>créée par <b>{{ task.user.username|default('anonymous user') }}</b></p>
                    <p>{{ task.content }}</p>
                </div>
                <div class="my-1">
                    <form action="{{ path('task_toggle', {'id' : task.id }) }}">
                        <button class="btn btn-success btn-sm pull-right">
                            {% if not task.isDone %}Marquer comme faite{% else %}Marquer non terminée{% endif %}
                        </button>
                    </form>
                    {% if is_granted('delete', task) %}
                        <form action="{{ path('task_delete', {'id' : task.id }) }}">
                            <button class="btn btn-danger btn-sm pull-right mr-2">Supprimer</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                Il n'y a pas encore de tâche enregistrée. <a href="{{ path('task_create') }}" class="btn btn-warning pull-right">Créer une tâche</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}